version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment:
      PORT: 5000
      FLASK_APP: "/usr/src/app/app.py"
      DATABASE_URL: "mysql://user:password@db/db"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql:/var/lib/mysql

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m flask db upgrade
    environment:
      FLASK_APP: "/usr/src/app/application.py"
      DATABASE_URL: "mysql://user:password@db/db"
    depends_on:
      - db

volumes:
  mysql:
